### ISSUE TITLE
Use transit engine from GH action

### ISSUE THREAD

**Issue by marcofranssen** [hashicorp/vault-action#249]
**Is your feature request related to a problem? Please describe.**

Currently there is no documentation on the transit engine, or to only use the action to authenticate a shell.

**Describe the solution you'd like**

I would like to be able to authenticate my workflow with hashicorp vault to use `cosign` for signing a docker image using the `transit` engine. This requires an authenticated shell. e.g. `VAULT_TOKEN` is set.

**Describe alternatives you've considered**

Alternative would be to write the login and installation of vault cli myself without using this action.

**Additional context**

**Comment by semihural-tomtom** [comment]
@marcofranssen how did you achieve to do this?

**Comment by marcofranssen** [comment]
> @marcofranssen how did you achieve to do this?

I didn't, hence the feature request.

**Comment by fairclothjm** [comment]
@marcofranssen Hello, thanks for the feature request! Unfortunately, this is out of scope for this project. Please see https://github.com/hashicorp/vault-action?tab=readme-ov-file#other-secret-engines

Vault Action currently supports retrieving secrets from any engine where secrets are retrieved via GET requests. This means secret engines such as Transit are currently not supported due to their requirement of sending parameters along with the request.
