### ISSUE TITLE
[FEAT] Clarify caCertificate in documentation

### ISSUE THREAD

**Issue by nferch** [hashicorp/vault-action#452]
The documentation for `caCertificate` should be expanded to be less ambiguous, especially compared to other systems with a similar parameter. Specifically: when configuring for the first time, I was left wondering:

- Why does `caCertificate` need to be Base64 encoded when certificates are already PEM encoded? It is unusual to require Base64 encoding for data that couldn't be binary. The other configuration parameters don't require Base64.
- Is `caCertificate` always required? Or is it only required when I have my own CA? If I'm using a standard CA, does the action make use of the standard CA bundle?

**Comment by WoodyWoodsta** [comment]
@nferch Do you know the answers to these? :) Specifically the second question. I have vault exposed behind a proxy using a letsencrypt certificate. My assumption is that this known CA should already be trusted.

**Comment by fairclothjm** [comment]
@nferch @WoodyWoodsta Hello! vault-action uses the [got](https://github.com/sindresorhus/got) library. The vault-action `caCertificate` field is used to set got's [https.certificateAuthority](https://github.com/sindresorhus/got/blob/main/documentation/5-https.md#certificateauthority) option. This Overrides trusted CA certificates and defaults to CAs provided by [Mozilla](https://ccadb-public.secure.force.com/mozilla/IncludedCACertificateReport). So it is not required and the table [here](https://github.com/hashicorp/vault-action#reference) documents it as such.

In regards to base64 encoding, I don't have a great answer. It may have been done that way due to limitations of GitHub's core action library. But I don't know for sure.
